version: "3"
services:
  flask-app:
    hostname: splunk-test-app
    environment:
      - HOSTNAME=0.0.0.0
      - SPLUNK_TOKEN=147d3b46-e7c9-456a-ad0c-5a79b2f2ffea
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - "splunk"
  splunk:
    hostname: splunk
    image: splunk/splunk
    env_file:
      - splunk.env
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"
